apiVersion: v1
kind: Service
metadata:
  name: springboot-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: springboot-app 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 3000 #The port for the Spring Boot application container